server:
  port: 80

eureka:
  client:
    # 將自己註冊到eureka server
    register-with-eureka: false
    # 從eureka索取註冊的服務
    #    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka.com:7001/eureka,http://eureka2.com:7002/eureka

feign:
  hystrix:
    enabled: true
