server:
  port: 8001

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

eureka:
  client:
    # 將自己註冊到eureka server
    register-with-eureka: true
    # 從eureka索取註冊的服務
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka.com:7001/eureka,http://eureka2.com:7002/eureka
  instance:
    instance-id: payment1
    prefer-ip-address: true
    # client端向server端發送心跳的間隔
    lease-renewal-interval-in-seconds: 1
    # server端收到最後一次心跳後，等待下次心跳的時間上限，超時將剔除服務。
    lease-expiration-duration-in-seconds: 2


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.samshih.springcloud.entities

